config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'quotes#index'
  resources :quotes
  get 'about', to: 'quotes#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
  validates :saying, presence: true, length: { maximum: 140, minimum: 3 }
  validates :author, presence: true, length: { maximum: 50, minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quote = Quote.order("Random()").first
  end

  ## (moved code to application.html.erb)
  # def new
  #   @quote = Quote.new
  # end

  def create
    @quote = Quote.create(quote_params)
    if @quote.invalid?
      flash[:error] = '<strong>Could not save</strong> the data you entered is invalid.'
    end
    redirect_to root_path
  end

  def about
  end

  private

  def quote_params
    params.require(:quote).permit(:saying, :author)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Splurty</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <header class="row">
      <div class="col-3">
        <%= link_to root_path, class: 'logo' do %>
          <div class="circle">
            <br />
            hahaha
            <br />
            for real
            <br />
            tho
          </div>
        <% end %>
      </div>
      <div class="col col-sm-4 hidden-xs-down slogan">
        It's funny because it's true.
      </div>
      <div class="col-10 offset-1 offset-sm-0 col-sm-5 links">
        <!-- Button trigger modal -->
        <%= link_to 'Contribute', '#', data: {toggle: 'modal', target: '#myModal'} %>
        <!-- <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
          Launch demo modal
        </button> -->
        <!-- <%= link_to 'Contribute', new_quote_path %> -->
        &nbsp;&nbsp;
        <%= link_to 'About', about_path %>
      </div>
    </header>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">Contribute Your Quote</h4>
          </div>
          <%= simple_form_for Quote.new do |f| %>
            <div class="modal-body">
              <%= f.input :saying, label: "Give me a quote that's both funny and true-to-life...", placeholder: "Men don't care what's on TV. They only care what else is on TV." %>
              <br />
              <%= f.input :author, label: "...and the clown who said it.", placeholder: "Jerry Seinfeld" %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= f.submit 'Create', class: 'btn btn-danger' %>
            </div>s
          <% end %>
        </div>
      </div>
    </div>    

    <hr />
    
    <br class="clear" />

    <div class="container">
      <% if flash[:error].present? %>
        <div class="col-10 offset-1 alert alert-danger">
          <%= flash[:error].html_safe %>
        </div>
      <% end %>
      <%= yield %>
    </div>

    <div class="footer">
      <div class="container">
        <div class="row">
          <div class="col-12 col-sm-6">
            <%= link_to "This isn't enough, I need more", root_path, class: 'next-quote' %>
          </div>
          <div class="col-12 col-sm-6 footer-blurb">
            Assembled with love by <a href="https://github.com/nnadkarny">Nikhil</a> in Delaware, which is totally a real state.<br />
            Want to build your own Splurty Web App? <a href="http://thefirehoseproject.com">Learn how to code here</a>. #noplugshame
          </div>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/quotes/about.html.erb
<div class="col-10 offset-1 about">
  <h1>About Splurty</h1>

  <p>
    Splurty was built by <a target="_blank" href="https://github.com/nnadkarny">Nikhil</a>, an exciting new web developer.  He thinks comedians tell the truth better than anyone, so he decided to make an app about it.
  </p>
  <br />
  <p>
    He says his next app will leave this one in the dust.  I believe him.
  </p>
  <p>
    If you want to learn how to code - start <a target="_blank" href="http://www.thefirehoseproject.com/"> here</a>.  If they can teach Nikhil, they can teach anyone.
  </p>

  <div class="row">
    <div class="col-12 col-sm-4">
      <%= image_tag 'nikhil.jpg', class: 'img-fluid' %>
    </div>

    <div class="col-12 col-sm-7 offset-sm-1">
      <h2 class="text-center">Nikhil Nadkarny</h2>
      <br />
      <p>
        Nikhil’s been a jack-of-all-trades IT engineer for several years/companies, and his coding toolbelt is growing heavier by the day.  He's been a geek-of-all-trades since birth.
      </p>
    </div>
  </div>

</div>

<br class="clear" />
<br />
<br />
<br />
<br />

app/views/quotes/index.html.erb
<h2>
  <span>Splurty / No. <%= @quote.id %></span>
  Here's one...
</h2>

<h1><%= @quote.saying %></h1>
<h2 class="float-right"><%= @quote.author %></h2>

<br class="clear" />
<br />
<br />
<br />